AWSTemplateFormatVersion: 2010-09-09
Description: A cloudformation template that creates an ECS Fargate cluster, running a docker container (you must push the docker container yourself).

Parameters:
  ContainerPort:
    Type: Number
    Description: The port the application is running on within the docker container
    MinValue: 1
  EcrRepositoryUri:
    Type: String
    Description: URI of image to run within ECS Task definition
    MinLength: 1
  HealthCheckPath:
    Type: String
    Description: Specify a path for the loadbalancer to determine if a node is healthy
    MinLength: 1
    Default: /
  LoadBalancerPort:
    Type: Number
    Description: The port the load balancer will forward requests from
    MinValue: 1
    Default: 80
  NamePrefix:
    Type: String
    Description: Prefix for naming resources and name tags
    Default: cf-ecs-fargate
    MinLength: 1

Resources:
  # VPC and contained Subnets
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, vpc ] ]
        - Key: source
          Value: !Ref AWS::StackName
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Join
        - ''
        - - !Ref AWS::Region
          - a
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, public-subnet-a ] ]
        - Key: source
          Value: !Ref AWS::StackName
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Join
        - ''
        - - !Ref AWS::Region
          - b
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, public-subnet-b ] ]
        - Key: source
          Value: !Ref AWS::StackName

  # Route Table and Internet Gateways
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, internet-gateway ] ]
        - Key: source
          Value: !Ref AWS::StackName
  InternetGatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, route-table ] ]
        - Key: source
          Value: !Ref AWS::StackName
  RouteInternet:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable
  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref PublicSubnetA
  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref PublicSubnetB

  # ECR Repository
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Join [ '-', [ !Ref NamePrefix, ecr-repository ] ]
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, ecr-repository ] ]
        - Key: source
          Value: !Ref AWS::StackName

  # ECS Cluster, Services and Tasks
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join [ '-', [ !Ref NamePrefix, cluster ] ]
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, cluster ] ]
        - Key: source
          Value: !Ref AWS::StackName
  EcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsCluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 60
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: !Join [ '-', [ !Ref NamePrefix, container ] ]
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref LoadBalancerTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref EcsContainerSecurityGroup
          Subnets:
            - !Ref PublicSubnetA
            - !Ref PublicSubnetB
      SchedulingStrategy: REPLICA
      ServiceName: !Join [ '-', [ !Ref NamePrefix, service] ]
      TaskDefinition: !Ref EcsTaskDefinition
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, service] ]
        - Key: source
          Value: !Ref AWS::StackName
  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: EcsTaskLogGroup
    Properties:
      ContainerDefinitions:
        - Cpu: 256
          Image: !Ref EcrRepositoryUri
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref EcsTaskLogGroup
              awslogs-stream-prefix: !Ref NamePrefix
          Memory: 512
          MemoryReservation: 512
          Name: !Join [ '-', [ !Ref NamePrefix, container ] ]
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
      Cpu: 256
      ExecutionRoleArn: !Ref EcsTaskExecutionRole
      Family: !Join [ '-', [ !Ref NamePrefix, task ] ]
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, task ] ]
        - Key: source
          Value: !Ref AWS::StackName

  # logs
  EcsTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [ '-', [ !Ref NamePrefix, log-group ] ]
      RetentionInDays: 7

  # Load Balancer
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Join [ '-', [ !Ref NamePrefix, load-balancer ] ]
      Scheme: internet-facing
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
      Type: application
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, load-balancer ] ]
        - Key: source
          Value: !Ref AWS::StackName
  LoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckPort: 8080
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: 200 # TODO: Health check will fail as it cannot hit the endpoint due to authorisation required in app.
      Name: !Join [ '-', [ !Ref NamePrefix, target-group ] ]
      Port: !Ref ContainerPort
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60
      TargetType: ip
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, load-balancer-target-group ] ]
        - Key: source
          Value: !Ref AWS::StackName
  LoadBalancerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref LoadBalancerTargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref LoadBalancerPort
      Protocol: HTTP

  # IAM Roles
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role used for ecs task execution
      RoleName: !Join [ '-', [ !Ref NamePrefix, role-task-execution ] ]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ecs-tasks.amazonaws.com ]
            Action: [ 'sts:AssumeRole' ]
      Path: /
      Policies:
        - PolicyName: !Join [ '-', [ !Ref NamePrefix, role-task-execution-policy ] ]
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ecs:CreateCluster'
                  - 'ecs:DeregisterContainerInstance'
                  - 'ecs:DiscoverPollEndpoint'
                  - 'ecs:Poll'
                  - 'ecs:RegisterContainerInstance'
                  - 'ecs:StartTelemetrySession'
                  - 'ecs:Submit*'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchGetImage'
                  - 'ecr:GetDownloadUrlForLayer'
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, role-task-execution ] ]
        - Key: source
          Value: !Ref AWS::StackName

  # Security Groups
  EcsContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join [ '-', [ !Ref 'AWS::StackName', container-security-group ] ]
      GroupName: !Join [ '-', [ !Ref NamePrefix, container-security-group ] ]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join [ '-', [ !Ref NamePrefix, container-security-group ] ]
        - Key: source
          Value: !Ref AWS::StackName
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join [ '-', [ !Ref 'AWS::StackName', load-balancer-security-group ] ]
      GroupName: !Join [ '-', [ !Ref NamePrefix, load-balancer-security-group ] ]
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: !Ref LoadBalancerPort
          ToPort: !Ref LoadBalancerPort
      VpcId: !Ref VPC
